services:
  registry:
    build:
      context: ../
      dockerfile: Regestry/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - KAFKA_BROKER=${KAFKA_IP}:9094
    command: ["python3", "/app/Regestry/EC_Registry.py"]
    networks:
      - easycab_shared_network

  taxi1:
    build:
      context: ../
      dockerfile: Taxi/Dockerfile
    environment:
      - KAFKA_BROKER=${KAFKA_IP}:9094
      - TERM=xterm
    command:
      ["python3", "/app/Taxi/EC_DE.py",
       "--ip_ecc_host", "central",
       "--ip_ecc_port", "65432",
       "--kafka_broker", "${KAFKA_IP}:9094",
       "--ip_port_ecs", "registry:5002",
       "--taxi_id", "1"]
    depends_on:
      - registry
    networks:
      - easycab_shared_network

  taxi2:
    build:
      context: ../
      dockerfile: Taxi/Dockerfile
    environment:
      - KAFKA_BROKER=${KAFKA_IP}:9094
      - TERM=xterm
    command:
      ["python3", "/app/Taxi/EC_DE.py",
       "--ip_ecc_host", "central",
       "--ip_ecc_port", "65432",
       "--kafka_broker", "${KAFKA_IP}:9094",
       "--ip_port_ecs", "registry:5002",
       "--taxi_id", "2"]
    depends_on:
      - registry
    networks:
      - easycab_shared_network

  taxi3:
    build:
      context: ../
      dockerfile: Taxi/Dockerfile
    environment:
      - KAFKA_BROKER=${KAFKA_IP}:9094
      - TERM=xterm
    command:
      ["python3", "/app/Taxi/EC_DE.py",
       "--ip_ecc_host", "central",
       "--ip_ecc_port", "65432",
       "--kafka_broker", "${KAFKA_IP}:9094",
       "--ip_port_ecs", "registry:5002",
       "--taxi_id", "3"]
    depends_on:
      - registry
    networks:
      - easycab_shared_network

  taxi4:
    build:
      context: ../
      dockerfile: Taxi/Dockerfile
    environment:
      - KAFKA_BROKER=${KAFKA_IP}:9094
      - TERM=xterm
    command:
      ["python3", "/app/Taxi/EC_DE.py",
       "--ip_ecc_host", "central",
       "--ip_ecc_port", "65432",
       "--kafka_broker", "${KAFKA_IP}:9094",
       "--ip_port_ecs", "registry:5002",
       "--taxi_id", "4"]
    depends_on:
      - registry
    networks:
      - easycab_shared_network

networks:
  easycab_shared_network:
    name: easycab_shared_network
    external: true
