version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - easycab_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${PC1_IP}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${PC1_IP}:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "taxi_positions:1:1,customer_requests:1:1,taxi_status:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - easycab_network

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=${PC1_IP}
      - KAFKA_PORT=9092
    networks:
      - easycab_network

networks:
  easycab_network:
    driver: bridge