version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easycab
      MYSQL_USER: easycab
      MYSQL_PASSWORD: easycab123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - easycab_network

  central:
    build:
      context: .
      dockerfile: central/Dockerfile
    environment:
      KAFKA_HOST: ${KAFKA_IP}  # IP de Kafka desde el archivo .env
      CENTRAL_PORT: 50051
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: easycab
      DB_PASSWORD: easycab123
    ports:
      - "50051:50051"
    depends_on:
      - mysql
    networks:
      - easycab_network

networks:
  easycab_network:
    driver: bridge

volumes:
  mysql_data:

env_file:
  - ./config.env
