services:
  central:
    build:
      context: .
      dockerfile: central/Dockerfile
    environment:
      - KAFKA_HOST=192.168.56.123
      - KAFKA_PORT=9092
      - CENTRAL_HOST=0.0.0.0
      - CENTRAL_PORT=50051
    ports:
      - "0.0.0.0:50051:50051"
    volumes:
      - ./data:/app/data
    networks:
      - easycab_network

networks:
  easycab_network:
    driver: bridge