services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - easycab_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "0.0.0.0:9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.56.123:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "taxi_positions:1:1,customer_requests:1:1,taxi_status:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - easycab_network

  central:
    build:
      context: .
      dockerfile: central/Dockerfile
    environment:
      - KAFKA_HOST=192.168.56.123
      - KAFKA_PORT=9092
      - CENTRAL_HOST=0.0.0.0
      - CENTRAL_PORT=50051
    ports:
      - "0.0.0.0:50051:50051"
    depends_on:
      - kafka
    networks:
      - easycab_network

networks:
  easycab_network:
    driver: bridge