version: '3'
services:
  taxi_de:
    build:
      context: .
      dockerfile: taxi/Dockerfile
    environment:
      KAFKA_IP: ${KAFKA_IP}  # IP de Kafka desde el archivo .env
      CENTRAL_IP: ${CENTRAL_IP}
      TAXI_ID: "1"
    depends_on:
      - central
    networks:
      - easycab_network

  taxi_sensor:
    build:
      context: ./taxi
      dockerfile: Dockerfile
    environment:
      TAXI_ID: "1"
      DE_HOST: taxi_de
      DE_PORT: 50053
    depends_on:
      - taxi_de
    networks:
      - easycab_network

networks:
  easycab_network:
    driver: bridge

env_file:
  - ./config.env
