# Imagen base
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY EC_S.py .
COPY kafka_utils.py .
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "EC_S.py"]
