FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY EC_DE.py .
COPY map_utils.py .
COPY kafka_utils.py .
COPY socket_protocol.py .

CMD ["python", "EC_DE.py"]