services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9094:9094"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_IP}:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  central:
    build:
      context: ..
      dockerfile: ./Central/Dockerfile
    ports:
      - "65432:65432"
    environment:
      - KAFKA_BROKER=kafka:29092
    command:
      - /bin/sh
      - -c
      - "sleep 10 && python3 /app/Central/EC_Central.py --listen_port 65432 --ip_port_broker kafka:29092"
    depends_on:
      - kafka

  front:
    build:
      context: ../
      dockerfile: ./WebVisualization/Dockerfile
    ports:
      - "8080:8080"
      - "8765:8765"
    volumes:
      - ../WebVisualization:/app/WebVisualization
    environment:
      KAFKA_BROKER: kafka:29092
    depends_on:
      kafka:
        condition: service_started
    command: >
      bash -c "
      python3 /app/WebVisualization/app.py &
      sleep 15 && python3 /app/WebVisualization/map_websocket_proxy.py --kafka_broker kafka:29092
      "